#!/bin/sh

./prepare "$@" &&
make -j10 IGNORE_ERRORS="n m" BUILD_LOG=1 BUILD_LOG_DIR=bin/logs

# SmartEye-Service:
# echo "CONFIG_TARGET_ar71xx_generic_TLMR3220=y\nCONFIG_PACKAGE_loee-SmartEye-Service=y" > .config &&
